modLoader = "javafml"
loaderVersion = "[47,)"
license = "${mod_license}"
showAsResourcePack = false
issueTrackerURL = "${mod_url_issue}"

[[mods]]
modId = "leawind_third_person"
version = "${mod_version}"
displayName = "${mod_name}"
description = "${mod_description}"
authors = "${mod_authors}"
logoFile = "TODO"
displayURL = "${mod_url_home}"

[[dependencies.leawind_third_person]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "CLIENT"
referraUrl = "https://files.minecraftforge.net/"

[[dependencies.leawind_third_person]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
referraUrl = "https://www.minecraft.net/"

[[dependencies.leawind_third_person]]
modId = "architectury"
mandatory = true
versionRange = "(,${architectury_version}]"
ordering = "AFTER"
side = "CLIENT"
referraUrl = "https://modrinth.com/mod/architectury-api"

[[dependencies.leawind_third_person]]
modId = "cloth_config"
mandatory = false
versionRange = "*"
ordering = "NONE"
side = "CLIENT"
referraUrl = "https://modrinth.com/mod/cloth-config"
